/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package spa;

import javax.swing.table.DefaultTableModel;

/**
 *
 * @author tifui
 */
public class VisualExample extends javax.swing.JFrame {

    /**
     * Creates new form VisualExample
     */
    public VisualExample() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_example = new javax.swing.JTable();
        jButton_showExample = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Student Alocation Problem");

        jLabel2.setText("Input Table:");

        jTable_example.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Student Preferences", "Lecturer Prefereneces", "Available Projects"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                true, true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable_example);

        jButton_showExample.setText("Show Example");
        jButton_showExample.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_showExampleActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 508, Short.MAX_VALUE)))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton_showExample)
                .addGap(23, 23, 23))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                .addComponent(jButton_showExample)
                .addGap(28, 28, 28))
        );

        jTabbedPane1.addTab("Example", jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTabbedPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_showExampleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_showExampleActionPerformed
       
        Project p1=new Project("P1");
        p1.setCapacity(2);
        Project p2=new Project("P2");
        p2.setCapacity(1);
        Project p3=new Project("P3");
        p3.setCapacity(1);
        Project p4=new Project("P4");
        p4.setCapacity(1);
        Project p5=new Project("P5");
        p5.setCapacity(1);
        Project p6=new Project("P6");
        p6.setCapacity(1);
        Project p7=new Project("P7");
        p7.setCapacity(1);
        Project p8=new Project("P8");
        p8.setCapacity(1);
        Lecturer l1=new Lecturer("L1");
        l1.setCapacity(3);
        l1.addProjects(p1,p2,p3);
        Lecturer l2=new Lecturer("L2");
        l2.setCapacity(2);
        l2.addProjects(p4,p5,p6);
        Lecturer l3=new Lecturer("L3");
        l3.setCapacity(2);
        l3.addProjects(p7,p8);
        Student s1=new Student("S1");
        s1.addProjects(p1,p7);
        Student s2=new Student("S2");
        s2.addProjects(p1,p2,p3,p4,p5,p6);
        Student s3=new Student("S3");
        s3.addProjects(p2,p1,p4);
        Student s4=new Student("S4");
        s4.addProjects(p2);
        Student s5=new Student("S5");
        s5.addProjects(p1,p2,p3,p4);
        Student s6=new Student("S6");
        s6.addProjects(p2,p3,p4,p5,p6);
        Student s7=new Student("S7");
        s7.addProjects(p5,p3,p8);
        l1.addPreferedStudents(s7,s4,s1,s3,s2,s5,s6);
        l2.addPreferedStudents(s3,s2,s6,s7,s5);
        l3.addPreferedStudents(s1,s7);
                
        
        DefaultTableModel model = (DefaultTableModel) jTable_example.getModel();
        model.getDataVector().removeAllElements();
                
        model.addRow(new Object[]{s1.toString(),l1.toString(),l1.getOferedProjectsString()});
        model.addRow(new Object[]{s2.toString(),l2.toString(),l2.getOferedProjectsString()});
        model.addRow(new Object[]{s3.toString(),l3.toString(),l3.getOferedProjectsString()});
        model.addRow(new Object[]{s4.toString()});
        model.addRow(new Object[]{s5.toString()});
        model.addRow(new Object[]{s6.toString()});
        model.addRow(new Object[]{s7.toString()});
        
    }//GEN-LAST:event_jButton_showExampleActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VisualExample.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VisualExample.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VisualExample.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VisualExample.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VisualExample().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_showExample;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable_example;
    // End of variables declaration//GEN-END:variables
}
