package gui;


/**
 *
 * @author tifui
 */
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JSpinner;
import javax.swing.JTextArea;
import javax.swing.table.DefaultTableModel;
import wordgame.LeterBag;
import wordgame.WordGame;


public class MainForm extends javax.swing.JFrame {

    /**
     * Creates new form MainForm
     */
    LeterBag leterBag;
    WordGame game;
    public MainForm() {
        initComponents();
        game=new WordGame(this,(int)spinner_nrPlayers.getValue(),table_lettersDistribution,
                          jPanel_player1,jPanel_player2,3);
        
        leterBag=game.getLeterBag();
        DefaultTableModel model=(DefaultTableModel) table_lettersDistribution.getModel();
        setLettersOntable(model,leterBag.getLeterDistribution());
  
    }
    
    public JSpinner getDifiSpinner()
    {
        return spiner_dificulty;
    }
    
    public JSpinner getPlayersSpinner()
    {
        return spinner_nrPlayers;
    }
    public  JButton getStopButton()
    {
        return button_stop;
    }
    public JButton getStartButton()
    {
        return Button_start;
    }
    
    public JButton getInitButton()
    {
        return button_initialize;
    }
    
    public JLabel[] getLabelsClasament()
    {
        JLabel[] labels=new JLabel[4];
        labels[0]=label_locul1;
        labels[1]=label_locul2;
        labels[2]=label_locul3;
        labels[3]=label_locul4;
        return labels;
    }
    
    public JLabel getTileLabel()
    {
        return label_time;
    }
    
    public JLabel getLabelLocul1()
    {
        return label_locul1;
    }
    public JLabel getLabelLocul2()
    {
        return label_locul2;
    }
    public JLabel getLabelLocul3()
    {
        return label_locul3;
    }
     public JLabel getLabelLocul4()
    {
        return label_locul4;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        table_lettersDistribution = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        spinner_nrPlayers = new javax.swing.JSpinner();
        jLabel3 = new javax.swing.JLabel();
        label_time = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Button_start = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel_player3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        player3_nume = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        player3_score = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        player3_titles = new javax.swing.JLabel();
        player3_curent = new javax.swing.JLabel();
        jPanel_player1 = new javax.swing.JPanel();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        player1_nume = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        player1_score = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        player1_titles = new javax.swing.JLabel();
        player1_curent = new javax.swing.JLabel();
        jPanel_player4 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        player4_nume = new javax.swing.JLabel();
        player4_score = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        player4_titles = new javax.swing.JLabel();
        player4__curent = new javax.swing.JLabel();
        jPanel_player2 = new javax.swing.JPanel();
        jLabel64 = new javax.swing.JLabel();
        jLabel65 = new javax.swing.JLabel();
        player2_nume = new javax.swing.JLabel();
        jLabel67 = new javax.swing.JLabel();
        player2_score = new javax.swing.JLabel();
        jLabel69 = new javax.swing.JLabel();
        jLabel70 = new javax.swing.JLabel();
        player2_titles = new javax.swing.JLabel();
        player2_curent = new javax.swing.JLabel();
        spiner_dificulty = new javax.swing.JSpinner();
        game_pane = new javax.swing.JPanel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        label_locul1 = new javax.swing.JLabel();
        label_locul2 = new javax.swing.JLabel();
        label_locul3 = new javax.swing.JLabel();
        label_locul4 = new javax.swing.JLabel();
        button_initialize = new javax.swing.JButton();
        button_stop = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        text_words = new javax.swing.JTextArea();
        jLabel41 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        table_lettersDistribution.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "", "", "", "", "", "", "", "", "", ""
            }
        ));
        jScrollPane1.setViewportView(table_lettersDistribution);

        jLabel1.setText("Letter distributions:");

        jLabel2.setText("Number of players:");

        spinner_nrPlayers.setModel(new javax.swing.SpinnerNumberModel(2, 2, 4, 1));
        spinner_nrPlayers.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spinner_nrPlayersStateChanged(evt);
            }
        });
        spinner_nrPlayers.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                spinner_nrPlayersPropertyChange(evt);
            }
        });

        jLabel3.setText("Elaspsed time:");

        label_time.setText("00:00");

        jLabel4.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(143, 44, 54));
        jLabel4.setText("Word Game");

        Button_start.setText("Start Game");
        Button_start.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_startActionPerformed(evt);
            }
        });

        jPanel_player3.setBackground(new java.awt.Color(202, 123, 37));

        jLabel7.setText("Player 3");

        jLabel20.setText("Nume:");

        player3_nume.setText("-");

        jLabel27.setText("Score");

        player3_score.setText("-");

        jLabel29.setText("Titles:");

        jLabel30.setText("Curent:");

        player3_titles.setText("-");

        player3_curent.setText("-");

        javax.swing.GroupLayout jPanel_player3Layout = new javax.swing.GroupLayout(jPanel_player3);
        jPanel_player3.setLayout(jPanel_player3Layout);
        jPanel_player3Layout.setHorizontalGroup(
            jPanel_player3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_player3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_player3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_player3Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel_player3Layout.createSequentialGroup()
                        .addGroup(jPanel_player3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel_player3Layout.createSequentialGroup()
                                .addComponent(jLabel20)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(player3_nume, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel_player3Layout.createSequentialGroup()
                                .addComponent(jLabel27)
                                .addGap(18, 18, 18)
                                .addComponent(player3_score))
                            .addGroup(jPanel_player3Layout.createSequentialGroup()
                                .addComponent(jLabel29)
                                .addGap(18, 18, 18)
                                .addComponent(player3_titles))
                            .addGroup(jPanel_player3Layout.createSequentialGroup()
                                .addComponent(jLabel30)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(player3_curent, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(12, 18, Short.MAX_VALUE))))
        );
        jPanel_player3Layout.setVerticalGroup(
            jPanel_player3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_player3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addGroup(jPanel_player3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(player3_nume, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_player3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(player3_score))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_player3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel29)
                    .addComponent(player3_titles))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_player3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel30)
                    .addComponent(player3_curent))
                .addContainerGap(115, Short.MAX_VALUE))
        );

        jPanel_player1.setBackground(new java.awt.Color(188, 74, 72));

        jLabel46.setText("Player 1");

        jLabel47.setText("Nume:");

        player1_nume.setText("-");

        jLabel49.setText("Score");

        player1_score.setText("-");

        jLabel51.setText("Titles:");

        jLabel52.setText("Curent:");

        player1_titles.setText("-");

        player1_curent.setText("-");

        javax.swing.GroupLayout jPanel_player1Layout = new javax.swing.GroupLayout(jPanel_player1);
        jPanel_player1.setLayout(jPanel_player1Layout);
        jPanel_player1Layout.setHorizontalGroup(
            jPanel_player1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_player1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_player1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_player1Layout.createSequentialGroup()
                        .addComponent(jLabel46)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel_player1Layout.createSequentialGroup()
                        .addGroup(jPanel_player1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel_player1Layout.createSequentialGroup()
                                .addComponent(jLabel47)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(player1_nume, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel_player1Layout.createSequentialGroup()
                                .addComponent(jLabel49)
                                .addGap(18, 18, 18)
                                .addComponent(player1_score))
                            .addGroup(jPanel_player1Layout.createSequentialGroup()
                                .addComponent(jLabel51)
                                .addGap(18, 18, 18)
                                .addComponent(player1_titles))
                            .addGroup(jPanel_player1Layout.createSequentialGroup()
                                .addComponent(jLabel52)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(player1_curent, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(12, 18, Short.MAX_VALUE))))
        );
        jPanel_player1Layout.setVerticalGroup(
            jPanel_player1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_player1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel46)
                .addGap(18, 18, 18)
                .addGroup(jPanel_player1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel47)
                    .addComponent(player1_nume, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_player1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel49)
                    .addComponent(player1_score))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_player1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel51)
                    .addComponent(player1_titles))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_player1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel52)
                    .addComponent(player1_curent))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel_player4.setBackground(new java.awt.Color(220, 24, 35));

        jLabel8.setText("Player 4");

        jLabel33.setText("Nume:");

        jLabel34.setText("Score");

        player4_nume.setText("-");

        player4_score.setText("-");

        jLabel37.setText("Titles:");

        jLabel38.setText("Curent:");

        player4_titles.setText("-");

        player4__curent.setText("-");

        javax.swing.GroupLayout jPanel_player4Layout = new javax.swing.GroupLayout(jPanel_player4);
        jPanel_player4.setLayout(jPanel_player4Layout);
        jPanel_player4Layout.setHorizontalGroup(
            jPanel_player4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_player4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_player4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addGroup(jPanel_player4Layout.createSequentialGroup()
                        .addComponent(jLabel33)
                        .addGap(18, 18, 18)
                        .addComponent(player4_nume))
                    .addGroup(jPanel_player4Layout.createSequentialGroup()
                        .addComponent(jLabel34)
                        .addGap(18, 18, 18)
                        .addComponent(player4_score))
                    .addGroup(jPanel_player4Layout.createSequentialGroup()
                        .addComponent(jLabel37)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(player4_titles))
                    .addGroup(jPanel_player4Layout.createSequentialGroup()
                        .addComponent(jLabel38)
                        .addGap(18, 18, 18)
                        .addComponent(player4__curent)))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        jPanel_player4Layout.setVerticalGroup(
            jPanel_player4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_player4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addGroup(jPanel_player4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel33)
                    .addComponent(player4_nume))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_player4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel34)
                    .addComponent(player4_score))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_player4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel37)
                    .addComponent(player4_titles))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_player4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel38)
                    .addComponent(player4__curent))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel_player2.setBackground(new java.awt.Color(199, 36, 40));

        jLabel64.setText("Player 2");

        jLabel65.setText("Nume:");

        player2_nume.setText("-");

        jLabel67.setText("Score");

        player2_score.setText("-");

        jLabel69.setText("Titles:");

        jLabel70.setText("Curent:");

        player2_titles.setText("-");

        player2_curent.setText("-");

        javax.swing.GroupLayout jPanel_player2Layout = new javax.swing.GroupLayout(jPanel_player2);
        jPanel_player2.setLayout(jPanel_player2Layout);
        jPanel_player2Layout.setHorizontalGroup(
            jPanel_player2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_player2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_player2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_player2Layout.createSequentialGroup()
                        .addComponent(jLabel64)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel_player2Layout.createSequentialGroup()
                        .addGroup(jPanel_player2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel_player2Layout.createSequentialGroup()
                                .addComponent(jLabel65)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(player2_nume, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel_player2Layout.createSequentialGroup()
                                .addComponent(jLabel67)
                                .addGap(18, 18, 18)
                                .addComponent(player2_score))
                            .addGroup(jPanel_player2Layout.createSequentialGroup()
                                .addComponent(jLabel69)
                                .addGap(18, 18, 18)
                                .addComponent(player2_titles))
                            .addGroup(jPanel_player2Layout.createSequentialGroup()
                                .addComponent(jLabel70)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(player2_curent, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(12, 18, Short.MAX_VALUE))))
        );
        jPanel_player2Layout.setVerticalGroup(
            jPanel_player2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_player2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel64)
                .addGap(18, 18, 18)
                .addGroup(jPanel_player2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel65)
                    .addComponent(player2_nume, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_player2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel67)
                    .addComponent(player2_score))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_player2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel69)
                    .addComponent(player2_titles))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_player2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel70)
                    .addComponent(player2_curent))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel_player1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jPanel_player2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel_player3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel_player4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_player3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel_player4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel_player1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel_player2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        spiner_dificulty.setModel(new javax.swing.SpinnerNumberModel(3, 3, 6, 1));
        spiner_dificulty.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spiner_dificultyStateChanged(evt);
            }
        });
        spiner_dificulty.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                spiner_dificultyPropertyChange(evt);
            }
        });

        jLabel42.setText("Locul 1:");

        jLabel43.setText("Locul 2:");

        jLabel44.setText("Locul 3:");

        jLabel45.setText("Locul 4:");

        label_locul1.setText("-");

        label_locul2.setText("-");

        label_locul3.setText("-");

        label_locul4.setText("-");

        javax.swing.GroupLayout game_paneLayout = new javax.swing.GroupLayout(game_pane);
        game_pane.setLayout(game_paneLayout);
        game_paneLayout.setHorizontalGroup(
            game_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(game_paneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(game_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(game_paneLayout.createSequentialGroup()
                        .addGroup(game_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel43)
                            .addComponent(jLabel42))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(game_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(game_paneLayout.createSequentialGroup()
                                .addComponent(label_locul1)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, game_paneLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(label_locul2))))
                    .addGroup(game_paneLayout.createSequentialGroup()
                        .addGroup(game_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(game_paneLayout.createSequentialGroup()
                                .addComponent(jLabel44)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(label_locul3))
                            .addGroup(game_paneLayout.createSequentialGroup()
                                .addComponent(jLabel45)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(label_locul4)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap(79, Short.MAX_VALUE))
        );
        game_paneLayout.setVerticalGroup(
            game_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(game_paneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(game_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel42)
                    .addComponent(label_locul1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(game_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel43)
                    .addComponent(label_locul2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(game_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel44)
                    .addComponent(label_locul3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(game_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel45)
                    .addComponent(label_locul4))
                .addContainerGap(54, Short.MAX_VALUE))
        );

        button_initialize.setText("Initialize");
        button_initialize.setEnabled(false);
        button_initialize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_initializeActionPerformed(evt);
            }
        });

        button_stop.setText("Stop");
        button_stop.setBorderPainted(false);
        button_stop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_stopActionPerformed(evt);
            }
        });

        text_words.setColumns(20);
        text_words.setRows(5);
        jScrollPane3.setViewportView(text_words);

        jLabel41.setText("Dificulty:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(spinner_nrPlayers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(label_time)
                            .addComponent(Button_start)
                            .addComponent(button_initialize)
                            .addComponent(button_stop))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)))
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel41)
                    .addComponent(game_pane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spiner_dificulty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel41))
                        .addGap(25, 25, 25)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(spinner_nrPlayers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(label_time)
                        .addGap(3, 3, 3)
                        .addComponent(button_initialize)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Button_start)
                        .addGap(2, 2, 2)
                        .addComponent(button_stop))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(spiner_dificulty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(game_pane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 16, Short.MAX_VALUE))
                    .addComponent(jScrollPane3))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Button_startActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_startActionPerformed
        
        button_initialize.setEnabled(false);
        spiner_dificulty.setEnabled(false);
        spinner_nrPlayers.setEnabled(false);
        Button_start.setEnabled(false);
        button_stop.setEnabled(true);
        
        Thread game_thread=new Thread(game);
        game_thread.start();
    }//GEN-LAST:event_Button_startActionPerformed

    public JTextArea getTextWordsCreated()
    {
        return  text_words;
    }
    
    private void spinner_nrPlayersPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_spinner_nrPlayersPropertyChange
        int nrPlayers=(int)spinner_nrPlayers.getValue();
        if(nrPlayers==2)
        {
            
            jPanel_player3.setVisible(false);
            jPanel_player4.setVisible(false);
        }
        if(nrPlayers==3)
        {
            jPanel_player3.setVisible(true);
            jPanel_player4.setVisible(false);
        }
        if(nrPlayers==4)
        {
            jPanel_player3.setVisible(true);
            jPanel_player4.setVisible(true);
        }
        
        
    }//GEN-LAST:event_spinner_nrPlayersPropertyChange

    private void spinner_nrPlayersStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spinner_nrPlayersStateChanged
             button_initialize.setEnabled(true);
                     int nrPlayers=(int)spinner_nrPlayers.getValue();
        if(nrPlayers==2)
        {
            
            jPanel_player3.setVisible(false);
            jPanel_player4.setVisible(false);
        }
        if(nrPlayers==3)
        {
            jPanel_player3.setVisible(true);
            jPanel_player4.setVisible(false);
        }
        if(nrPlayers==4)
        {
            jPanel_player3.setVisible(true);
            jPanel_player4.setVisible(true);
        }
    }//GEN-LAST:event_spinner_nrPlayersStateChanged

    private void spiner_dificultyPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_spiner_dificultyPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_spiner_dificultyPropertyChange

    private void spiner_dificultyStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spiner_dificultyStateChanged
        button_initialize.setEnabled(true);
    }//GEN-LAST:event_spiner_dificultyStateChanged

    private void button_initializeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_initializeActionPerformed
        int nrPlayers=(int)spinner_nrPlayers.getValue();
        text_words.setText("");
        Button_start.setEnabled(true);
        if(nrPlayers==2)
         game=new WordGame(this,nrPlayers,table_lettersDistribution,
                            jPanel_player1,jPanel_player2,(int)spiner_dificulty.getValue());
        if(nrPlayers==3)
         game=new WordGame(this,nrPlayers,table_lettersDistribution,
                          jPanel_player1,jPanel_player2,jPanel_player3,(int)spiner_dificulty.getValue());
        if(nrPlayers==4)
         game=new WordGame(this,nrPlayers,table_lettersDistribution,
                          jPanel_player1,jPanel_player2,jPanel_player3,jPanel_player4,(int)spiner_dificulty.getValue());
        
        leterBag=game.getLeterBag();
        DefaultTableModel model=(DefaultTableModel) table_lettersDistribution.getModel();
        setLettersOntable(model,leterBag.getLeterDistribution());
    }//GEN-LAST:event_button_initializeActionPerformed

    private void InitializeLabels()
    {
        label_locul1.setText("-");
        label_locul2.setText("-");
        label_locul3.setText("-");
        label_locul4.setText("-");
      
        
        
        
    }
    
    private void button_stopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_stopActionPerformed
       game.StopGame();
       button_initialize.setEnabled(true);
       Button_start.setEnabled(true);
       button_stop.setEnabled(false);
       spiner_dificulty.setEnabled(true);
       spiner_dificulty.setEnabled(true);
    }//GEN-LAST:event_button_stopActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new MainForm().setVisible(true);
        });
    }
    
    /**
     * Seteaza matricea cu literele de distributie in tabel.
     * @param model Modelul tabelului
     * @param letterDist  Matricea de distributie ce va fi setata
     */
    private void setLettersOntable(DefaultTableModel model,char[][] letterDist)
    {
        model.getDataVector().clear();
        for (char[] letterRow : letterDist) {
           
            String[] strings=new String[letterDist.length];
            for(int i=0;i<letterRow.length;i++)
            {
                strings[i]=""+letterRow[i];
            }
            model.addRow(strings);
           
           
        }
    }
     
   public JLabel getLabel_namePlayer(int nr)
   {
       if(nr==1)
       {
         return player1_nume;
       }
       if(nr==2)
       {
         return player2_nume;
       }
       if(nr==3)
       {
         return player3_nume;
       }
       if(nr==4)
       {
         return player4_nume;
       }
       return null;
       
   }
   public JLabel getLabel_scorePlayer(int nr)
   {
       if(nr==1)
       {
         return player1_score;
       }
       if(nr==2)
       {
         return player2_score;
       }
       if(nr==3)
       {
         return player3_score;
       }
       if(nr==4)
       {
         return player4_score;
       }
       return null;
       
   }
      public JLabel getLabel_titlesPlayer(int nr)
   {
       if(nr==1)
       {
         return player1_titles;
       }
       if(nr==2)
       {
         return player2_titles;
       }
       if(nr==3)
       {
         return player3_titles;
       }
       if(nr==4)
       {
         return player4_titles;
       }
       return null;
       
   }
         public JLabel getLabel_curentPlayer(int nr)
   {
       if(nr==1)
       {
         return player1_curent;
       }
       if(nr==2)
       {
         return player2_curent;
       }
       if(nr==3)
       {
         return player3_curent;
       }
       if(nr==4)
       {
         return player4__curent;
       }
       return null;
       
   }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Button_start;
    private javax.swing.JButton button_initialize;
    private javax.swing.JButton button_stop;
    private javax.swing.JPanel game_pane;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JLabel jLabel67;
    private javax.swing.JLabel jLabel69;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel70;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel_player1;
    private javax.swing.JPanel jPanel_player2;
    private javax.swing.JPanel jPanel_player3;
    private javax.swing.JPanel jPanel_player4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel label_locul1;
    private javax.swing.JLabel label_locul2;
    private javax.swing.JLabel label_locul3;
    private javax.swing.JLabel label_locul4;
    private javax.swing.JLabel label_time;
    private javax.swing.JLabel player1_curent;
    private javax.swing.JLabel player1_nume;
    private javax.swing.JLabel player1_score;
    private javax.swing.JLabel player1_titles;
    private javax.swing.JLabel player2_curent;
    private javax.swing.JLabel player2_nume;
    private javax.swing.JLabel player2_score;
    private javax.swing.JLabel player2_titles;
    private javax.swing.JLabel player3_curent;
    private javax.swing.JLabel player3_nume;
    private javax.swing.JLabel player3_score;
    private javax.swing.JLabel player3_titles;
    private javax.swing.JLabel player4__curent;
    private javax.swing.JLabel player4_nume;
    private javax.swing.JLabel player4_score;
    private javax.swing.JLabel player4_titles;
    private javax.swing.JSpinner spiner_dificulty;
    private javax.swing.JSpinner spinner_nrPlayers;
    private javax.swing.JTable table_lettersDistribution;
    private javax.swing.JTextArea text_words;
    // End of variables declaration//GEN-END:variables
}
