

package gestiuneangajati;
import java.util.List;
import javafx.scene.control.Label;
import javax.swing.DefaultListModel;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.JTabbedPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author tifui
 */



public class MainForm extends javax.swing.JFrame {

    /**
     * Creates new form MainForm
     */
    GestiuneAngajati gestiune;
    String CaleFiserSerializat="//home//tifui//Descărcări//IP//save.ser";
    
    public MainForm() {
        initComponents();
        gestiune=new GestiuneAngajati();
        gestiune=GestiuneAngajati.GetAngajatiFromSerializedFile(CaleFiserSerializat);
        if(gestiune==null)
        {
             gestiune=new GestiuneAngajati();
        }
        createTree();
       
    }   
    
    public void createTree()
    {
        DefaultMutableTreeNode root=new DefaultMutableTreeNode("Gestiune Angajati");
        DefaultTreeModel treeModel=new DefaultTreeModel(root);
        DefaultMutableTreeNode treeNode,treeNode1,treeNode2,treeNode3,treeNode4,treeNode5,treeNode6,treeNode7,treeNode8,treeNode9,treeNode10;       
        treeNode=new DefaultMutableTreeNode("Manageri");
        root.add(treeNode);
        for(Manager manager :gestiune.getManageri())
        {   
            treeNode2=new DefaultMutableTreeNode(manager.getNume()+" "+manager.getPrenume());
            treeNode3=new DefaultMutableTreeNode("Sefi grupe:");
            treeNode.add(treeNode2);
            treeNode2.add(treeNode3);
            for(SefGrupa sefGrupa:manager.getSefiGrupe())
            {   
                
                treeNode4=new DefaultMutableTreeNode(sefGrupa.getNume()+" "+sefGrupa.getPrenume());
                treeNode3.add(treeNode4);
                 treeNode5=new DefaultMutableTreeNode("Sef Echipe:");
                 treeNode4.add(treeNode5);
                
                for(SefEchipa sefEchipa:sefGrupa.getSefiEchipe())
                {
                    treeNode6=new DefaultMutableTreeNode(sefEchipa.getNume()+" "+sefEchipa.getPrenume());
                    treeNode5.add(treeNode6);
                     treeNode7=new DefaultMutableTreeNode("Programatori:");
                     treeNode8=new DefaultMutableTreeNode("Testeri");
                     treeNode6.add(treeNode7);
                     treeNode6.add(treeNode8);
                    
                    for(Programator programator:sefEchipa.getProgramatoriSubordonati())
                    {
                        treeNode9=new DefaultMutableTreeNode(programator.getNume()+" "+programator.getPrenume());
                        treeNode7.add(treeNode9);
                    }
                    
                    
                    for(Tester tester:sefEchipa.getTesteriSubordonati())
                    {
                        treeNode10=new DefaultMutableTreeNode(tester.getNume()+" "+tester.getPrenume());
                        treeNode8.add(treeNode10);
                    }
                    
                }
            }
        }
        
        
        jTree_Angajati.setModel(treeModel);
    }
    
    public void refreshManageriTable()
    {
         DefaultTableModel model=(DefaultTableModel) jTable_angajati.getModel();
            
            for(int i=model.getRowCount()-1;i>-1;i--)
            {
                model.removeRow(i);
            }
            for(Manager manager:gestiune.getManageri())
              { 
                 
                model.addRow(manager.getDetaliiAngajat());
                
                
              }
            jTable_angajati.setModel(model);
            jTable_angajati.doLayout();
    }
    
   


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        label_tipAngajat = new javax.swing.JLabel();
        jSplitPane1 = new javax.swing.JSplitPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTree_Angajati = new javax.swing.JTree();
        Jtabbed_panel = new javax.swing.JTabbedPane();
        panel_lista = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable_angajati = new javax.swing.JTable();
        jLabel41 = new javax.swing.JLabel();
        jComboBox_tipAfisare = new javax.swing.JComboBox<>();
        panel_adauga = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jText_nume = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jText_prenume = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jText_adresa = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        Jtext_functie = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jText_telefon = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jText_salariu = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jText_nume_SefEchipa = new javax.swing.JTextField();
        jText_prenume_SefEchipa = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jText_adresa_sefEchipa = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        Jtext_functie2 = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jText_telefon_sefEchipa = new javax.swing.JTextField();
        jButton_adaugaSefEchipa = new javax.swing.JButton();
        jText_salariu_sefEchipa = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jComboBox_manageri_AddsefEchipa = new javax.swing.JComboBox<>();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jComboBox_sefiGrupe = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jText_nume_SefGrupa = new javax.swing.JTextField();
        jText_prenume_SefGrupa = new javax.swing.JTextField();
        jText_adresa_sefGrupa = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        Jtext_functie1 = new javax.swing.JTextField();
        jText_telefon_sefGrupa = new javax.swing.JTextField();
        jButton_adaugaSefGrupa = new javax.swing.JButton();
        jText_salariu_sefGrupa = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jComboBox_manageri = new javax.swing.JComboBox<>();
        jPanel5 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jText_nume_Programator = new javax.swing.JTextField();
        jText_prenume_Programator = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jText_adresa_Programator = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        Jtext_functie3 = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jText_telefon_Programator = new javax.swing.JTextField();
        jButton_adaugaSefGrupa2 = new javax.swing.JButton();
        jText_salariu_programator = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jComboBox_addProgramator_manageri = new javax.swing.JComboBox<>();
        jLabel30 = new javax.swing.JLabel();
        jComboBox_addProgramator_SefiGrupe = new javax.swing.JComboBox<>();
        jLabel31 = new javax.swing.JLabel();
        jComboBox_addProgramator_sefiEchipe = new javax.swing.JComboBox<>();
        jPanel6 = new javax.swing.JPanel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jComboBox_addTester_manageri = new javax.swing.JComboBox<>();
        jText_prenume_Tester = new javax.swing.JTextField();
        jText_nume_Tester = new javax.swing.JTextField();
        jLabel35 = new javax.swing.JLabel();
        jText_adresa_tester = new javax.swing.JTextField();
        jLabel36 = new javax.swing.JLabel();
        jComboBox_addtester_SefiGrupe = new javax.swing.JComboBox<>();
        jText_telefon_Tester = new javax.swing.JTextField();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        Jtext_functie4 = new javax.swing.JTextField();
        jLabel39 = new javax.swing.JLabel();
        jButton_adaugaSefGrupa3 = new javax.swing.JButton();
        jText_salariu_tester = new javax.swing.JTextField();
        jComboBox_addTester_sefiEchipe = new javax.swing.JComboBox<>();
        jLabel40 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jLabel1.setText("Gestiune Angajati");

        jSplitPane1.setDividerLocation(180);
        jSplitPane1.setDividerSize(10);

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("Manageri");
        javax.swing.tree.DefaultMutableTreeNode treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Sefi de echipa");
        javax.swing.tree.DefaultMutableTreeNode treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Sefi de grupa");
        javax.swing.tree.DefaultMutableTreeNode treeNode4 = new javax.swing.tree.DefaultMutableTreeNode("Programatori");
        treeNode3.add(treeNode4);
        treeNode4 = new javax.swing.tree.DefaultMutableTreeNode("Testeri");
        treeNode3.add(treeNode4);
        treeNode2.add(treeNode3);
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Alti Angajati");
        treeNode1.add(treeNode2);
        jTree_Angajati.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jTree_Angajati.addTreeSelectionListener(new javax.swing.event.TreeSelectionListener() {
            public void valueChanged(javax.swing.event.TreeSelectionEvent evt) {
                Jtree_Angajat_valueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(jTree_Angajati);

        jSplitPane1.setLeftComponent(jScrollPane1);

        Jtabbed_panel.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                Jtabbed_panelStateChanged(evt);
            }
        });

        jTable_angajati.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nume", "Prenume", "Functie", "Adresa", "Telefon", "Salariu"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane3.setViewportView(jTable_angajati);

        jLabel41.setText("Tip:");

        jComboBox_tipAfisare.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Manageri", "Sefi de grupa", "Sefi de echipa", "Programatori", "Testeri", "Alti Angajati" }));
        jComboBox_tipAfisare.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_tipAfisareActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_listaLayout = new javax.swing.GroupLayout(panel_lista);
        panel_lista.setLayout(panel_listaLayout);
        panel_listaLayout.setHorizontalGroup(
            panel_listaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_listaLayout.createSequentialGroup()
                .addGroup(panel_listaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 708, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panel_listaLayout.createSequentialGroup()
                        .addComponent(jLabel41)
                        .addGap(1, 1, 1)
                        .addComponent(jComboBox_tipAfisare, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 191, Short.MAX_VALUE))
        );
        panel_listaLayout.setVerticalGroup(
            panel_listaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_listaLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(panel_listaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel41)
                    .addComponent(jComboBox_tipAfisare, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        Jtabbed_panel.addTab("Lista", panel_lista);

        jLabel2.setText("Nume:");

        jLabel3.setText("Prenume:");

        jLabel4.setText("Adresa:");

        jLabel5.setText("Functie(optional):");

        jLabel6.setText("Telefon:");

        jLabel7.setText("Salariu:");

        jButton1.setText("Adauga Angajat");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jText_nume, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(63, 63, 63)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jText_prenume, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel4)
                    .addComponent(jText_adresa)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(Jtext_functie, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabel7)
                            .addComponent(jText_salariu, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(70, 70, 70)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jText_telefon)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(513, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jText_nume, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jText_prenume, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jText_adresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Jtext_functie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jText_telefon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jText_salariu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jButton1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panel_adaugaLayout = new javax.swing.GroupLayout(panel_adauga);
        panel_adauga.setLayout(panel_adaugaLayout);
        panel_adaugaLayout.setHorizontalGroup(
            panel_adaugaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panel_adaugaLayout.setVerticalGroup(
            panel_adaugaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        Jtabbed_panel.addTab("Adauga manager", panel_adauga);

        jLabel15.setText("Nume:");

        jLabel16.setText("Prenume:");

        jLabel17.setText("Adresa:");

        jLabel18.setText("Functie(optional):");

        Jtext_functie2.setText("Sef Echipa");

        jLabel19.setText("Telefon:");

        jButton_adaugaSefEchipa.setText("Adauga Angajat");
        jButton_adaugaSefEchipa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_adaugaSefEchipaActionPerformed(evt);
            }
        });

        jLabel20.setText("Salariu:");

        jComboBox_manageri_AddsefEchipa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_manageri_AddsefEchipaActionPerformed(evt);
            }
        });

        jLabel27.setText("Manager:");

        jLabel28.setText("Sef grupa:");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15)
                            .addComponent(jText_nume_SefEchipa, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(63, 63, 63)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16)
                            .addComponent(jText_prenume_SefEchipa, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel17)
                    .addComponent(jText_adresa_sefEchipa)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(Jtext_functie2, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel18, javax.swing.GroupLayout.Alignment.LEADING))
                            .addComponent(jLabel20)
                            .addComponent(jText_salariu_sefEchipa, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(70, 70, 70)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jText_telefon_sefEchipa)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton_adaugaSefEchipa, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(36, 36, 36)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel27)
                    .addComponent(jComboBox_manageri_AddsefEchipa, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel28)
                    .addComponent(jComboBox_sefiGrupe, 0, 146, Short.MAX_VALUE))
                .addContainerGap(331, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jLabel16)
                    .addComponent(jLabel27))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jText_nume_SefEchipa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jText_prenume_SefEchipa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox_manageri_AddsefEchipa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(jLabel28))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jText_adresa_sefEchipa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox_sefiGrupe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(jLabel19))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Jtext_functie2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jText_telefon_sefEchipa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel20)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jText_salariu_sefEchipa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jButton_adaugaSefEchipa)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Jtabbed_panel.addTab("Adauga Sef Echipa", jPanel4);

        jLabel8.setText("Nume:");

        jLabel9.setText("Prenume:");

        jLabel10.setText("Adresa:");

        jLabel11.setText("Functie(optional):");

        jLabel12.setText("Telefon:");

        Jtext_functie1.setText("Sef Grupa");

        jButton_adaugaSefGrupa.setText("Adauga Angajat");
        jButton_adaugaSefGrupa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_adaugaSefGrupaActionPerformed(evt);
            }
        });

        jLabel13.setText("Salariu:");

        jLabel14.setText("Manager :");

        jComboBox_manageri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_manageriActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jText_nume_SefGrupa, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(63, 63, 63)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jText_prenume_SefGrupa, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel10)
                    .addComponent(jText_adresa_sefGrupa)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(Jtext_functie1, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabel13)
                            .addComponent(jText_salariu_sefGrupa, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(70, 70, 70)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jText_telefon_sefGrupa)
                            .addComponent(jButton_adaugaSefGrupa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(26, 26, 26)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addComponent(jComboBox_manageri, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jText_nume_SefGrupa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jText_prenume_SefGrupa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jText_adresa_sefGrupa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Jtext_functie1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jText_telefon_sefGrupa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jText_salariu_sefGrupa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addComponent(jButton_adaugaSefGrupa))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jComboBox_manageri, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Jtabbed_panel.addTab("Adauga Sef Grupa", jPanel3);

        jLabel21.setText("Nume:");

        jLabel22.setText("Prenume:");

        jLabel23.setText("Adresa:");

        jLabel24.setText("Functie(optional):");

        Jtext_functie3.setText("Sef Grupa");

        jLabel25.setText("Telefon:");

        jButton_adaugaSefGrupa2.setText("Adauga Angajat");
        jButton_adaugaSefGrupa2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_adaugaSefGrupa2ActionPerformed(evt);
            }
        });

        jLabel26.setText("Salariu:");

        jLabel29.setText("Maneger:");

        jComboBox_addProgramator_manageri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_addProgramator_manageriActionPerformed(evt);
            }
        });

        jLabel30.setText("Sef Grupa:");

        jComboBox_addProgramator_SefiGrupe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_addProgramator_SefiGrupeActionPerformed(evt);
            }
        });

        jLabel31.setText("Sef Echipa:");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel21)
                            .addComponent(jText_nume_Programator, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(63, 63, 63)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel22)
                            .addComponent(jText_prenume_Programator, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel23)
                    .addComponent(jText_adresa_Programator)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(Jtext_functie3, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel24, javax.swing.GroupLayout.Alignment.LEADING))
                            .addComponent(jLabel26)
                            .addComponent(jText_salariu_programator, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(70, 70, 70)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jText_telefon_Programator)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton_adaugaSefGrupa2, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(28, 28, 28)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel29)
                    .addComponent(jLabel30)
                    .addComponent(jComboBox_addProgramator_manageri, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jComboBox_addProgramator_SefiGrupe, 0, 163, Short.MAX_VALUE)
                    .addComponent(jLabel31)
                    .addComponent(jComboBox_addProgramator_sefiEchipe, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(322, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel21)
                            .addComponent(jLabel22))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jText_nume_Programator, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jText_prenume_Programator, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel23)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jText_adresa_Programator, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel24)
                            .addComponent(jLabel25))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Jtext_functie3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jText_telefon_Programator, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel26)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jText_salariu_programator, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addComponent(jButton_adaugaSefGrupa2))))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabel29)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jComboBox_addProgramator_manageri, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43)
                        .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox_addProgramator_SefiGrupe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel31)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jComboBox_addProgramator_sefiEchipe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(103, Short.MAX_VALUE))
        );

        Jtabbed_panel.addTab("Adauga Programator", jPanel5);

        jLabel32.setText("Nume:");

        jLabel33.setText("Prenume:");

        jLabel34.setText("Maneger:");

        jComboBox_addTester_manageri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_addTester_manageriActionPerformed(evt);
            }
        });

        jLabel35.setText("Adresa:");

        jLabel36.setText("Sef Grupa:");

        jComboBox_addtester_SefiGrupe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_addtester_SefiGrupeActionPerformed(evt);
            }
        });

        jLabel37.setText("Telefon:");

        jLabel38.setText("Functie(optional):");

        Jtext_functie4.setText("Sef Grupa");

        jLabel39.setText("Salariu:");

        jButton_adaugaSefGrupa3.setText("Adauga Angajat");
        jButton_adaugaSefGrupa3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_adaugaSefGrupa3ActionPerformed(evt);
            }
        });

        jLabel40.setText("Sef Echipa:");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel32)
                            .addComponent(jText_nume_Tester, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(63, 63, 63)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel33)
                            .addComponent(jText_prenume_Tester, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel35)
                    .addComponent(jText_adresa_tester)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(Jtext_functie4, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel38, javax.swing.GroupLayout.Alignment.LEADING))
                            .addComponent(jLabel39)
                            .addComponent(jText_salariu_tester, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(70, 70, 70)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jText_telefon_Tester)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel37, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton_adaugaSefGrupa3, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(28, 28, 28)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel34)
                    .addComponent(jLabel36)
                    .addComponent(jComboBox_addTester_manageri, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jComboBox_addtester_SefiGrupe, 0, 163, Short.MAX_VALUE)
                    .addComponent(jLabel40)
                    .addComponent(jComboBox_addTester_sefiEchipe, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(322, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel32)
                            .addComponent(jLabel33))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jText_nume_Tester, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jText_prenume_Tester, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel35)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jText_adresa_tester, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel38)
                            .addComponent(jLabel37))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Jtext_functie4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jText_telefon_Tester, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel39)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jText_salariu_tester, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addComponent(jButton_adaugaSefGrupa3))))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabel34)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jComboBox_addTester_manageri, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43)
                        .addComponent(jLabel36, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox_addtester_SefiGrupe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel40)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jComboBox_addTester_sefiEchipe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(103, Short.MAX_VALUE))
        );

        Jtabbed_panel.addTab("Adauga Tester", jPanel6);

        jSplitPane1.setRightComponent(Jtabbed_panel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSplitPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(57, 57, 57)
                        .addComponent(label_tipAngajat)
                        .addContainerGap(920, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(23, Short.MAX_VALUE)
                        .addComponent(label_tipAngajat)
                        .addGap(12, 12, 12))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)))
                .addComponent(jSplitPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Jtree_Angajat_valueChanged(javax.swing.event.TreeSelectionEvent evt) {//GEN-FIRST:event_Jtree_Angajat_valueChanged
        // TODO add your handling code here:
        if(evt.getNewLeadSelectionPath()==null)
            return;
      
        String node =evt.getNewLeadSelectionPath().getLastPathComponent().toString();
       
        label_tipAngajat.setText(node);
         /*
        if( node.equals("Manageri") ) 
        {
            
            Jtabbed_panel.setTitleAt(0,"Lista manageri:");
             DefaultTableModel model=(DefaultTableModel) jTable_angajati.getModel();
            Jtext_functie.setText(node);
            for(int i=model.getRowCount()-1;i>-1;i--)
            {
                model.removeRow(i);
            }
            for(Manager manager:gestiune.getManageri())
              { 
                 
                model.addRow(manager.getDetaliiAngajat());
               
                
              }
            jTable_angajati.setModel(model);
            jTable_angajati.doLayout();
           
        }  else Jtext_functie.setText("");
        */
        
    }//GEN-LAST:event_Jtree_Angajat_valueChanged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if(jTree_Angajati.getLeadSelectionPath()==null)
            return;
        if(jTree_Angajati.getLeadSelectionPath().getLastPathComponent().toString().equals("Manageri"))
        {
            try{
            //suntem pe manageri
            Manager manager=new Manager();
            manager.setAdresa(jText_adresa.getText());
            manager.setNume(jText_nume.getText());
            manager.setPrenume(jText_prenume.getText());
           
            manager.setSalariu(Float.parseFloat(jText_salariu.getText()));
            gestiune.addManager(manager);
            refreshManageriTable();
            }
            catch (Exception exc)
            {
                JOptionPane.showMessageDialog(rootPane,"Eroare :"+exc.toString());
            }
            
            createTree();
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
       
        gestiune.SalvareAngajati();
        
    }//GEN-LAST:event_formWindowClosing

    private void jButton_adaugaSefGrupaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_adaugaSefGrupaActionPerformed
        // TODO add your handling code here:
      SefGrupa sefGrupa=new SefGrupa(jText_nume_SefGrupa.getText(), jText_prenume_SefGrupa.getText());
      sefGrupa.setAdresa(jText_adresa_sefGrupa.getText());
      sefGrupa.setSalariu(Float.parseFloat(jText_salariu_sefGrupa.getText()));
      
      gestiune.getManageri().get(jComboBox_manageri.getSelectedIndex()).addSefEchipa(sefGrupa);
      createTree();
      
       
    }//GEN-LAST:event_jButton_adaugaSefGrupaActionPerformed

    private void jComboBox_manageriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_manageriActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jComboBox_manageriActionPerformed

    private void Jtabbed_panelStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_Jtabbed_panelStateChanged
        // TODO add your handling code here:
        JTabbedPane sourceTabbedPane = (JTabbedPane) evt.getSource();
        int index=sourceTabbedPane.getSelectedIndex();
        if(index==3)
        {
           if(gestiune==null)
               return;
           jComboBox_manageri.removeAllItems();
            for(Manager manager:gestiune.getManageri())
            {
              jComboBox_manageri.addItem(manager.getNume()+" "+manager.getPrenume());
            }
            
        }
        if(index==2)
        {   jComboBox_manageri_AddsefEchipa.removeAllItems();
            for(Manager man:gestiune.getManageri())
            {
                jComboBox_manageri_AddsefEchipa.addItem(man.getNumePrenume());
                
            }
        }
        if(index==4)
        {
             jComboBox_addProgramator_manageri.removeAllItems();
            for(Manager man:gestiune.getManageri())
            {
                jComboBox_addProgramator_manageri.addItem(man.getNumePrenume());
                
            }
        }
        if(index==5)
        {
             jComboBox_addTester_manageri.removeAllItems();
            for(Manager man:gestiune.getManageri())
            {
                jComboBox_addTester_manageri.addItem(man.getNumePrenume());
                
            }
        }
    }//GEN-LAST:event_Jtabbed_panelStateChanged

    private void jButton_adaugaSefEchipaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_adaugaSefEchipaActionPerformed
        // TODO add your handling code here:
        SefEchipa sefEchipa=new SefEchipa();
        sefEchipa.setAdresa(jText_adresa_sefEchipa.getText());
        sefEchipa.setNume(jText_nume_SefEchipa.getText());
        sefEchipa.setPrenume(jText_prenume_SefEchipa.getText());
        sefEchipa.setSalariu(Float.parseFloat(jText_salariu_sefEchipa.getText()));
       gestiune.getManageri().get(jComboBox_manageri_AddsefEchipa.getSelectedIndex()).getSefiGrupe().get(jComboBox_sefiGrupe.getSelectedIndex()).addSefEchipa(sefEchipa);
       createTree();
     
    }//GEN-LAST:event_jButton_adaugaSefEchipaActionPerformed

    private void jButton_adaugaSefGrupa2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_adaugaSefGrupa2ActionPerformed
        // TODO add your handling code here:
        Programator programator=new Programator();
        programator.setAdresa(jText_adresa_Programator.getText());
        programator.setNume(jText_nume_Programator.getText());
        programator.setPrenume(jText_prenume_Programator.getText());
        programator.setSalariu(Float.parseFloat(jText_salariu_programator.getText()));
        gestiune.getManageri().get(jComboBox_addProgramator_manageri.getSelectedIndex()).getSefiGrupe().get(jComboBox_addProgramator_sefiEchipe.getSelectedIndex()).getSefiEchipe().get(jComboBox_addProgramator_sefiEchipe.getSelectedIndex()).addProgramator(programator);
    }//GEN-LAST:event_jButton_adaugaSefGrupa2ActionPerformed

    private void jComboBox_manageri_AddsefEchipaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_manageri_AddsefEchipaActionPerformed
        // TODO add your handling code here:
        if(jComboBox_manageri_AddsefEchipa.getSelectedIndex()<0)
            return;
        jComboBox_sefiGrupe.removeAllItems();
        for(SefGrupa sefGrupa:gestiune.getManageri().get(jComboBox_manageri_AddsefEchipa.getSelectedIndex()).getSefiGrupe())
        {
            jComboBox_sefiGrupe.addItem(sefGrupa.getNumePrenume());
        }
        
    }//GEN-LAST:event_jComboBox_manageri_AddsefEchipaActionPerformed

    private void jComboBox_addProgramator_SefiGrupeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_addProgramator_SefiGrupeActionPerformed
        // TODO add your handling code here:
        if(jComboBox_manageri.getSelectedIndex()<0)
            return;
        if(jComboBox_addProgramator_SefiGrupe.getSelectedIndex()<0)
            return;
        jComboBox_addProgramator_sefiEchipe.removeAllItems();
        for(SefEchipa sefEchupa:gestiune.getManageri().get(jComboBox_addProgramator_manageri.getSelectedIndex()).getSefiGrupe().get(jComboBox_addProgramator_SefiGrupe.getSelectedIndex()).getSefiEchipe())
        {
            jComboBox_addProgramator_sefiEchipe.addItem(sefEchupa.getNumePrenume());
        }
    }//GEN-LAST:event_jComboBox_addProgramator_SefiGrupeActionPerformed

    private void jComboBox_addtester_SefiGrupeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_addtester_SefiGrupeActionPerformed
        // TODO add your handling code here:
        if(jComboBox_addtester_SefiGrupe.getSelectedIndex()<0)
            return;
        for(SefEchipa sefEchipa:gestiune.getManageri().get(jComboBox_addTester_manageri.getSelectedIndex()).getSefiGrupe().get(jComboBox_addtester_SefiGrupe.getSelectedIndex()).getSefiEchipe())
        {
            jComboBox_addTester_sefiEchipe.addItem(sefEchipa.getNumePrenume());
        }
    }//GEN-LAST:event_jComboBox_addtester_SefiGrupeActionPerformed

    private void jButton_adaugaSefGrupa3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_adaugaSefGrupa3ActionPerformed
        // TODO add your handling code here:
        if(jComboBox_addTester_sefiEchipe.getSelectedIndex()<0)
        {
            return;
        }
        Tester tester=new Tester();
        tester.setNume(jText_nume_Tester.getText());
        tester.setPrenume(jText_prenume_Tester.getText());
        tester.setAdresa(jText_adresa_tester.getText());
        tester.setSalariu(Float.parseFloat(jText_salariu_tester.getText()));
        gestiune.getManageri().get(jComboBox_addTester_manageri.getSelectedIndex()).getSefiGrupe().get(jComboBox_addtester_SefiGrupe.getSelectedIndex()).getSefiEchipe().get(jComboBox_addTester_sefiEchipe.getSelectedIndex()).addTester(tester);
        createTree();
    }//GEN-LAST:event_jButton_adaugaSefGrupa3ActionPerformed

    private void jComboBox_addProgramator_manageriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_addProgramator_manageriActionPerformed
        // TODO add your handling code here:
        if(jComboBox_addProgramator_manageri.getSelectedIndex()<0)
            return;
        jComboBox_addProgramator_SefiGrupe.removeAllItems();
        for(SefGrupa sefGrupa:gestiune.getManageri().get(jComboBox_addProgramator_manageri.getSelectedIndex()).getSefiGrupe())
        {
           jComboBox_addProgramator_SefiGrupe.addItem(sefGrupa.getNumePrenume());
        }
    }//GEN-LAST:event_jComboBox_addProgramator_manageriActionPerformed

    private void jComboBox_tipAfisareActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_tipAfisareActionPerformed
        // TODO add your handling code here:
       switch(jComboBox_tipAfisare.getSelectedIndex())
       {
           case 0:
           {
               refreshManageriTable();
               break;
           }
           case 1:
           {
               refreshSefiGrupeTable();
               break;
           }
           case 2:
           {
               refreshSefiEchipaTable();
              break; 
           }
           case 3:
           {
               refreshProgramatoriTable();
               break;
           }
           case 4:
           {
               refreshTesteriTable();
               break;
           }
               
                 
       }
        
    }//GEN-LAST:event_jComboBox_tipAfisareActionPerformed

    private void jComboBox_addTester_manageriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_addTester_manageriActionPerformed
        // TODO add your handling code here:
        jComboBox_addtester_SefiGrupe.removeAllItems();
        for(SefGrupa sefgrupa:gestiune.getManageri().get(jComboBox_addTester_manageri.getSelectedIndex()).getSefiGrupe())
        {
            jComboBox_addtester_SefiGrupe.addItem(sefgrupa.getNumePrenume());
        }
    }//GEN-LAST:event_jComboBox_addTester_manageriActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainForm().setVisible(true);
            }
        });
    }
    
    public void refreshSefiGrupeTable()
    {
         DefaultTableModel model=(DefaultTableModel) jTable_angajati.getModel();
            
            for(int i=model.getRowCount()-1;i>-1;i--)
            {
                model.removeRow(i);
            }
            for(Manager manager:gestiune.getManageri())
            {
        
                for(SefGrupa sefGrupa:manager.getSefiGrupe())
                 {
                   model.addRow(sefGrupa.getDetaliiAngajat());
                 }
            }
        
            jTable_angajati.setModel(model);
            jTable_angajati.doLayout();
          
    }
    
    public void refreshSefiGrupaTable()
    {
         DefaultTableModel model=(DefaultTableModel) jTable_angajati.getModel();
            
            for(int i=model.getRowCount()-1;i>-1;i--)
            {
                model.removeRow(i);
            }
            for(Manager manager:gestiune.getManageri())
            {
        
                for(SefGrupa sefGrupa:manager.getSefiGrupe())
                 {
                   model.addRow(sefGrupa.getDetaliiAngajat());
                 }
            }
        
            jTable_angajati.setModel(model);
            jTable_angajati.doLayout();
          
    }
    public void refreshSefiEchipaTable()
    {
         DefaultTableModel model=(DefaultTableModel) jTable_angajati.getModel();
            
            for(int i=model.getRowCount()-1;i>-1;i--)
            {
                model.removeRow(i);
            }
            for(Manager manager:gestiune.getManageri())
            {
        
                for(SefGrupa sefGrupa:manager.getSefiGrupe())
                 {
                   for(SefEchipa sefEchipa:sefGrupa.getSefiEchipe())
                   {
                       model.addRow(sefEchipa.getDetaliiAngajat());
                   }
                     
                 }
            }
        
            jTable_angajati.setModel(model);
            jTable_angajati.doLayout();
          
    } 
     public void refreshProgramatoriTable()
    {
         DefaultTableModel model=(DefaultTableModel) jTable_angajati.getModel();
            
            for(int i=model.getRowCount()-1;i>-1;i--)
            {
                model.removeRow(i);
            }
            for(Manager manager:gestiune.getManageri())
            {
        
                for(SefGrupa sefGrupa:manager.getSefiGrupe())
                 {
                   for(SefEchipa sefEchipa:sefGrupa.getSefiEchipe())
                   {
                       for(Programator prog:sefEchipa.getProgramatoriSubordonati())
                       {
                           model.addRow(prog.getDetaliiAngajat());
                       }
                   }
                     
                 }
            }
        
            jTable_angajati.setModel(model);
            jTable_angajati.doLayout();
          
    } 
     
    public void refreshTesteriTable()
    {
         DefaultTableModel model=(DefaultTableModel) jTable_angajati.getModel();
            
            for(int i=model.getRowCount()-1;i>-1;i--)
            {
                model.removeRow(i);
            }
            for(Manager manager:gestiune.getManageri())
            {
        
                for(SefGrupa sefGrupa:manager.getSefiGrupe())
                 {
                   for(SefEchipa sefEchipa:sefGrupa.getSefiEchipe())
                   {
                       for(Tester test:sefEchipa.getTesteriSubordonati())
                       {
                           model.addRow(test.getDetaliiAngajat());
                                 
                       }
                   }
                     
                 }
            }
        
            jTable_angajati.setModel(model);
            jTable_angajati.doLayout();
          
    } 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane Jtabbed_panel;
    private javax.swing.JTextField Jtext_functie;
    private javax.swing.JTextField Jtext_functie1;
    private javax.swing.JTextField Jtext_functie2;
    private javax.swing.JTextField Jtext_functie3;
    private javax.swing.JTextField Jtext_functie4;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton_adaugaSefEchipa;
    private javax.swing.JButton jButton_adaugaSefGrupa;
    private javax.swing.JButton jButton_adaugaSefGrupa2;
    private javax.swing.JButton jButton_adaugaSefGrupa3;
    private javax.swing.JComboBox<String> jComboBox_addProgramator_SefiGrupe;
    private javax.swing.JComboBox<String> jComboBox_addProgramator_manageri;
    private javax.swing.JComboBox<String> jComboBox_addProgramator_sefiEchipe;
    private javax.swing.JComboBox<String> jComboBox_addTester_manageri;
    private javax.swing.JComboBox<String> jComboBox_addTester_sefiEchipe;
    private javax.swing.JComboBox<String> jComboBox_addtester_SefiGrupe;
    private javax.swing.JComboBox<String> jComboBox_manageri;
    private javax.swing.JComboBox<String> jComboBox_manageri_AddsefEchipa;
    private javax.swing.JComboBox<String> jComboBox_sefiGrupe;
    private javax.swing.JComboBox<String> jComboBox_tipAfisare;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JTable jTable_angajati;
    private javax.swing.JTextField jText_adresa;
    private javax.swing.JTextField jText_adresa_Programator;
    private javax.swing.JTextField jText_adresa_sefEchipa;
    private javax.swing.JTextField jText_adresa_sefGrupa;
    private javax.swing.JTextField jText_adresa_tester;
    private javax.swing.JTextField jText_nume;
    private javax.swing.JTextField jText_nume_Programator;
    private javax.swing.JTextField jText_nume_SefEchipa;
    private javax.swing.JTextField jText_nume_SefGrupa;
    private javax.swing.JTextField jText_nume_Tester;
    private javax.swing.JTextField jText_prenume;
    private javax.swing.JTextField jText_prenume_Programator;
    private javax.swing.JTextField jText_prenume_SefEchipa;
    private javax.swing.JTextField jText_prenume_SefGrupa;
    private javax.swing.JTextField jText_prenume_Tester;
    private javax.swing.JTextField jText_salariu;
    private javax.swing.JTextField jText_salariu_programator;
    private javax.swing.JTextField jText_salariu_sefEchipa;
    private javax.swing.JTextField jText_salariu_sefGrupa;
    private javax.swing.JTextField jText_salariu_tester;
    private javax.swing.JTextField jText_telefon;
    private javax.swing.JTextField jText_telefon_Programator;
    private javax.swing.JTextField jText_telefon_Tester;
    private javax.swing.JTextField jText_telefon_sefEchipa;
    private javax.swing.JTextField jText_telefon_sefGrupa;
    private javax.swing.JTree jTree_Angajati;
    private javax.swing.JLabel label_tipAngajat;
    private javax.swing.JPanel panel_adauga;
    private javax.swing.JPanel panel_lista;
    // End of variables declaration//GEN-END:variables
}
